# Generated by Django 4.1.7 on 2023-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('text', models.TextField(default='Not Available', max_length=255)),
            ],
        ),
    ]
