# Generated by Django 4.1.7 on 2023-03-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
