# Generated by Django 4.1.7 on 2023-03-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_user_id_alter_user_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='exit', upload_to='images'),
            preserve_default=False,
        ),
    ]
